#!/usr/bin/bash

# this is the "0th" file in the tvbox launch chain
# ran by irexec
# runs tvbox

# prevent multiple instances
if [ $(pgrep -c irtvboxlaunch) -gt 1 ]; then
	echo "duplicate instance, abort"
	exit
fi

if [ -r "$XDG_CONFIG_HOME/tvboxrc" ]; then
  source "$XDG_CONFIG_HOME/tvboxrc"
elif [ -r ~/.config/tvboxrc ]; then
  # shellcheck source=tvboxrc.example
  source ~/.config/tvboxrc
else
  echo "Could not load tvboxrc, abort" >&2
  exit 1
fi

pkill -f 'python.*tvbox.*'
pkill -f 'feh.*tvbox.*'
pkill -f 'lxterminal.*tvbox.*'
killall tvbox
killall tvboxlaunchchain2
sleep 1
pkill -f -9 'python.*tvbox.*'
pkill -f -9 'feh.*tvbox.*'
pkill -f -9 'lxterminal.*tvbox.*'
killall -9 tvbox
killall -9 tvboxlaunchchain2

"$TVBOX_DIR/tvbox" #--no-delay
