#!/usr/bin/bash

# this is the "0th" file in the tvbox launch chain
# ran by irexec
# runs tvbox

# shellcheck source=tvbox.conf.example
source ~/.tvbox.conf

#TODO: make sure this actually kills everything, check lircrc too
#killall python3
#killall feh
#killall lxterminal
#killall tvbox
#killall tvboxlaunchchain2
pkill -f '.*tvbox.*'
sleep 1
pkill -f -9 '.*tvbox.*'
#killall -9 python3
#killall -9 feh
#killall -9 lxterminal
#killall -9 tvbox
#killall -9 tvboxlaunchchain2

$TVBOX_DIR/tvbox --no-delay
