#!/usr/bin/bash

# this is the first file in the tvbox launch chain
# can be run directly or by irtvboxlaunch
# runs tvboxlaunchchain2

# make sure it's not already running
if ps -ef | grep -v grep | grep "feh"; then
	echo "feh already running, abort" >&2
	exit 1
fi
if ps -ef | grep -v grep | grep "python3"; then
	echo "python3 already running, abort" >&2
	exit 1
fi


# splash screen
if [ "$1" != "--no-delay" ]; then
	feh -YF ~/tvbox/tvbox-splash.png &
	# this is to give it a chance to sync the time via NTP. ideally it should have an RTC.
	sleep 19
	killall feh
fi

# are we already in a terminal window?
if [ "$TERM" == "xterm-256color" ]; then
	~/tvbox/tvboxlaunchchain2
else
	lxterminal -t tvboxterm -e ~/tvbox/tvboxlaunchchain2
fi

