#!/usr/bin/bash

# this is to give it a chance to sync the time via NTP. ideally it should have an RTC.
sleep 10

wmctrl -r 'bash' -b add,maximized_vert,maximized_horz

python3 ~/tvbox/tvbox.py ~/tvbox_media/channels 2>&1 | tee ~/tvbox/tvbox.log

bash -i

