#!/usr/bin/bash

# this is the first file in the tvbox launch chain
# can be run directly or by irtvboxlaunch
# runs tvboxlaunchchain2.sh

if [ -r "$XDG_CONFIG_HOME/tvboxrc" ]; then
  source "$XDG_CONFIG_HOME/tvboxrc"
elif [ -r ~/.config/tvboxrc ]; then
  # shellcheck source=tvboxrc.example
  source ~/.config/tvboxrc
else
  echo "Could not load tvboxrc, abort" >&2
  exit 1
fi

# make sure it's not already running
if pgrep -fa 'feh.*tvbox.*'; then
	echo "feh tvbox already running, abort" >&2
	exit 1
fi
if pgrep -fa 'python.*tvbox.*'; then
	echo "python3 tvbox already running, abort" >&2
	exit 1
fi

# splash screen
if [ "$1" != "--no-delay" ]; then
	feh -F "$TVBOX_DIR/images/tvbox-splash.png" &
	# this is to give the raspi a chance to sync the time via NTP. ideally it should have an RTC.
	#TODO: make this check for NTP time sync to avoid having to wait the full timeout every time
	sleep "$TVBOX_SPLASH_TIMEOUT"
	pkill -f 'feh.*tvbox.*'
fi

# are we already in a terminal window?
if [ "$TERM" == "xterm-256color" ]; then
	bash "$TVBOX_DIR/tvboxlaunchchain2.sh"
else
	lxterminal -t tvboxterm -e "bash $TVBOX_DIR/tvboxlaunchchain2.sh"
fi
